language: rust
cache: cargo
jobs:
  include:
    - stage: test
      script:
        - cd rust
        - cargo test --all -- --test-threads=1
    - stage: build
      script:
        - cd rust
        - ./build-linux.sh
notifications:
  slack:
    rooms:
      - crowdmasterdevelopers:fDilAv0776bDAcSBGEJHGKyd
    on_success: change
    on_failure: always
  email: false
