language: rust
script:
  - cd rust
  - ./build-linux.sh
notifications:
  slack:
    rooms:
      - crowdmasterdevelopers:fDilAv0776bDAcSBGEJHGKyd
    on_success: change
    on_failure: always
  email: false
