language: rust
jobs:
  include:
    - stage: test
      script:
        - cd rust
        - cargo test --all
    - stage: build
      script:
        - cd rust
        - ./build-linux.sh
notifications:
  slack:
    rooms:
      - crowdmasterdevelopers:fDilAv0776bDAcSBGEJHGKyd
    on_success: change
    on_failure: always
  email: false
