[package]
name = "channel_sound"
version = "0.1.0"
authors = ["Peter-Noble <peter@noblesque.org.uk>", "John Roper <john@jmroper.com>"]

[lib]
name = "channel_sound"
crate-type = ["cdylib"]

[dependencies.cpython]
version = "*"
features = ["extension-module"]

