[package]
name = "channel_sound"
version = "0.1.0"
authors = ["Peter-Noble <peter@noblesque.org.uk>"]

[lib]
name = "channel_sound"
crate-type = ["cdylib"]

[dependencies.cpython]
version = "0.1"
features = ["extension-module"]

